**Primos de Mersenne y números perfectos.**

**a)**  Determina para qué valores de $n$ entre 1 y 10 son primos los números $M_n=2^n-1$. A la vista de los resultados, ¿te atreves a conjeturar cuándo lo serán para otros valores de $n$?  Los primos de la forma $M_n$ se denominan primos de Mersenne en memoria del filósofo del siglo XVII Marin Mersenne, quien los estudió en su obra *Cognitata Physico-Mathematica*.

In [4]:
for n in range(1,11):
    Mn = 2^n-1
    print(n,Mn,Mn in Primes())
    #print('{0:10}  {1:10} {2:10}'.format(Mn in Primes(), n, Mn))

1 1 False
2 3 True
3 7 True
4 15 False
5 31 True
6 63 False
7 127 True
8 255 False
9 511 False
10 1023 False


> **Conjetura** (sobre los primos de Mersenne) .... 
>
> Si n es primo entonces $M_n$ es primo

______________
**b)** Repite el apartado a) para $n$ entre 11 y 20. ¿Cambia tu conjetura?

In [5]:
for n in range(11,21):
    Mn = 2^n-1
    print(n,Mn,Mn in Primes())

11 2047 False
12 4095 False
13 8191 True
14 16383 False
15 32767 False
16 65535 False
17 131071 True
18 262143 False
19 524287 True
20 1048575 False


> **Conjetura** (sobre los primos de Mersenne) ....
>
> Si $M_n$ es primo, entonces $n$ es primo

_______________
**c)** Mersenne conjeturó que había una cantidad finita de primos de la forma $M_n$, concretamente los correspondientes a
$$
n=2,3,5,7,13,17,19,31,67,127,257.
$$
Mersenne se equivocó doblemente. Por una parte, no todos los $n$ de esta lista producen un primo. Detecta, con la ayuda de Sage, cuáles son los que no lo hacen. Por otra, hay primos de Mersenne correspondientes a valores de $n$ que no están en esta lista. Comprueba que ese es el caso si
$$
n=61, 89, 107, 521,607,1279.
$$

En septiembre de 2022 se conocían 51 primos de Mersenne. El mayor, $M_{82 589 933}$, era el mayor primo conocido hasta ese momento. No se sabe si hay más.

In [6]:
l = [2,3,5,7,13,17,19,31,67,127,257]
for n in l:
    if 2^n-1 not in Primes():
        print(n)

67
257


In [7]:
l = [61,89,107,521,607,1279]
for n in l:
    if 2^n-1 in Primes():
        print(n)

61
89
107
521
607
1279


In [9]:
Mn = 2^(82589933)-1
print(Mn in Primes())
#Esta instrucción comprobaría que efectivamente es primo. Pero habría que esperar demasiado tiempo. Para parar la ejecución de la celda hay que darle al cuadrado que está a la derecha del botón de play

KeyboardInterrupt: 

__________________
**d)**  Un número perfecto es un entero positivo que es igual a la suma de sus divisores propios positivos.
Así, 6 es un número perfecto porque sus divisores propios son 1, 2 y 3, y 6 = 1 + 2 + 3. Definir una función $\verb=perfecto(k)=$ que dado un entero positivo $\texttt{k}$ devuelva $\texttt{True}$ si $\texttt{k}$ es perfecto y $\texttt{False}$ en caso contrario.

*Sugerencia.* Puede ser útil usar el método $\texttt{divisors()}$.

In [12]:
def perfecto(k):
    if sum(divisors(k)) == 2*k:
        return True
    else:
        return False
print(perfecto(28))
print(perfecto(30))


True
False


__________________
**e)** Euclides ya sabía de la existencia de primos de Mersenne muchos siglos antes que este, y encontró una fuerte relación entre ellos y los números perfectos.  Concretamente,  el último resultado de la parte de teoría de números de sus *Elementos* establece que si $M$ es un  primo de Mersenne, entonces $M(M+1)/2$ es un número perfecto par. Comprueba esta afirmación para los diez primeros primos de Mersenne. 

*Observación previa:* por los apartados anteriores sé que $M_n$ es primo para 2, 3, 5, 7, 13, 17, 19, 31, 127 (conocido por Mersenne, apartado c)), y en el apartado d) lo hemos visto para 61, 89, 107, 521, 607, 1279. Es decir, los diez valores más pequeños de $n$ para los que sabemos que $M_n$ es primo son 2, 3, 5, 7, 13, 17, 19, 31, 61, 89. Realmente no sé seguro si estos son los diez primeros primos de Mersenne: voy a comprobarlo:



In [10]:
#obs previa
#Voy a almacenar todos los números de Mersenne Mn con n<90 en una lista que llamaré l:
l = []

for n in range(1,90):
    if n in Primes():
        Mn = 2^n-1
        if Mn in Primes():
            l.append(n)
l

[2, 3, 5, 7, 13, 17, 19, 31, 61, 89]

In [13]:
#Compruebo el apartado (a) para los 10 primeros primos de Mersenne (que son los de la lista l)
for n in l:
    Mn = 2^n - 1
    M = Mn*(Mn+1)/2
    print(perfecto(M) and (M % 2 == 0))

True
True
True
True
True
True
True
True
True
True


__________
**f)** Muchos siglos después, Euler demostró el recíproco: si un número $n$ es perfecto y par, entonces es de la forma $M(M+1)/2$ para algún primo de Mersenne. Obtén la lista de todos los números perfectos pares menores o iguales que $M_{13}(M_{13}+1)/2$ y comprueba que todos ellos son de la forma $M(M+1)/2$ para algún primo de Mersenne $M$.

In [ ]:
#lista de todos los perfectos pares menores que M13*...: (cuidado, a sage le lleva un tiempo)
mtrece = (2^13-1)*2^12
lista_perfectos_pares = []
for m in range(2,mtrece+1,2):
    if perfecto(m):
        lista_perfectos_pares.append(m)
lista_perfectos_pares


In [15]:

#lista de los M(M+1)/2 donde M es un primo de Mersenne menor que M13
lista_mersenne = []
for n in range(1,14):
    if 2^n-1 in Primes():
        lista_mersenne.append((2^n-1)* 2^(n-1))
lista_mersenne

[6, 28, 496, 8128, 33550336]

____________
**g)** A día de hoy no se sabe si hay algún número perfecto impar. Comprueba que no hay ninguno menor que un millón.

In [16]:
exito = False
for r in range(1,10^6,2):
    if perfecto(r):
        print('Eureka',r)
        exito = 'true'
if not exito:
    print('Su búsqueda no produjo resultados')
        

Su búsqueda no produjo resultados
