**Primos de Mersenne y números perfectos.**

**a)**  Determina para qué valores de $n$ entre 1 y 10 son primos los números $M_n=2^n-1$. A la vista de los resultados, ¿te atreves a conjeturar cuándo lo serán para otros valores de $n$?  Los primos de la forma $M_n$ se denominan primos de Mersenne en memoria del filósofo del siglo XVII Marin Mersenne, quien los estudió en su obra *Cognitata Physico-Mathematica*.

In [1]:
# Función que define si el número pasado como argumento es primo o no.
def is_prime(n):
  for i in range(2,n):
    if (n%i) == 0:
      return False
  return True

# Bucle del 1 al 10 en el que se imprimen los valores  
for n in range(1, 11):
    valor = (2**n) - 1
    if valor == 1:
        continue
    else:
        primo = is_prime(valor)
        if primo == True:
            print(f"Para el valor {n}, (2^n - 1) es primo.")

# De momento solo funciona para valores primos de n.
# print (valor in Primes()) también valdría para saber si el número es primo.

Para el valor 2, (2^n - 1) es primo.
Para el valor 3, (2^n - 1) es primo.
Para el valor 5, (2^n - 1) es primo.
Para el valor 7, (2^n - 1) es primo.


> **Conjetura** (sobre los primos de Mersenne) ....

______________
**b)** Repite el apartado a) para $n$ entre 11 y 20. ¿Cambia tu conjetura?

In [2]:
# Función que define si el número pasado como argumento es primo o no.
def is_prime(n):
  for i in range(2,n):
    if (n%i) == 0:
      return False
  return True

# Bucle del 1 al 10 en el que se imprimen los valores  
for n in range(11, 21):
    valor = (2**n) - 1
    if valor == 1:
        continue
    else:
        primo = is_prime(valor)
        if primo == True:
            print(f"Para el valor {n}, (2^n - 1) es primo.")

# En este caso el 11 no produce un número primo.

Para el valor 13, (2^n - 1) es primo.
Para el valor 17, (2^n - 1) es primo.
Para el valor 19, (2^n - 1) es primo.


_______________
**c)** Mersenne conjeturó que había una cantidad finita de primos de la forma $M_n$, concretamente los correspondientes a
$$
n=2,3,5,7,13,17,19,31,67,127,257.
$$
Mersenne se equivocó doblemente. Por una parte, no todos los $n$ de esta lista producen un primo. Detecta, con la ayuda de Sage, cuáles son los que no lo hacen. Por otra, hay primos de Mersenne correspondientes a valores de $n$ que no están en esta lista. Comprueba que ese es el caso si
$$
n=61, 89, 107, 521,607,1279.
$$

En septiembre de 2022 se conocen 51 primos de Mersenne. El mayor, $M_{82 589 933}$, es el mayor primo conocido hasta ese momento. No se sabe si hay más.

In [6]:
# Definimos la lista de números n
lista_n = [2, 3, 5, 7, 13, 17, 19, 31, 67, 127, 257]
show(lista_n)
# Hacemos igual que antes pero en este caso con la lista.
for n in lista_n:
    valor = (2**n) - 1
    if valor == 1:
        continue
    else:
        primo = is_prime(valor)
        if primo == True:
            show(f"Para el valor {n}, (2^n - 1) es primo.")

# Se equivocó en los números 67 y 257 ya que no conforman un número primo.

[2, 3, 5, 7, 13, 17, 19, 31, 67, 127, 257]

'Para el valor 2, (2^n - 1) es primo.'

'Para el valor 3, (2^n - 1) es primo.'

'Para el valor 5, (2^n - 1) es primo.'

'Para el valor 7, (2^n - 1) es primo.'

'Para el valor 13, (2^n - 1) es primo.'

'Para el valor 17, (2^n - 1) es primo.'

'Para el valor 19, (2^n - 1) es primo.'

'Para el valor 31, (2^n - 1) es primo.'

'Para el valor 127, (2^n - 1) es primo.'

In [7]:
# Definimos la lista de números n
lista_n = [61, 89, 107, 521, 607, 1279]
show(lista_n)
# Hacemos igual que antes pero en este caso con la lista.
for n in lista_n:
    valor = (2**n) - 1
    if valor == 1:
        continue
    else:
        primo = is_prime(valor)
        if primo == True:
            show(f"Para el valor {n}, (2^n - 1) es primo.")
show("Se cumple para todos los valores de la lista.")


[61, 89, 107, 521, 607, 1279]

'Para el valor 61, (2^n - 1) es primo.'

'Para el valor 89, (2^n - 1) es primo.'

'Para el valor 107, (2^n - 1) es primo.'

'Para el valor 521, (2^n - 1) es primo.'

'Para el valor 607, (2^n - 1) es primo.'

'Para el valor 1279, (2^n - 1) es primo.'

'Se cumple para todos los valores de la lista.'

__________________
**d)**  Un número perfecto es un entero positivo que es igual a la suma de sus divisores propios positivos.
Así, 6 es un número perfecto porque sus divisores propios son 1, 2 y 3, y 6 = 1 + 2 + 3. Definir una función $\verb=perfecto(k)=$ que dado un entero positivo $\texttt{k}$ devuelva $\texttt{True}$ si $\texttt{k}$ es perfecto y $\texttt{False}$ en caso contrario.

*Sugerencia.* Puede ser útil usar el método $\texttt{divisors()}$.

In [5]:
def perfecto(k):
    lista_divisores = divisors(k)
    longitud = len(lista_divisores)
    suma = 0
    for i in range(longitud-1):
        suma += lista_divisores[i]
    if suma == k:
        return True
    else:
        return False

k = int(input("Introduce un número: "))
resultado = perfecto(k)
if resultado == True:
    print("El número introducido es perfecto.")
else:
    print("El número introducido no es perfecto.")

Introduce un número:  6


El número introducido es perfecto.


__________________
**e)** Euclides ya sabía de la existencia de primos de Mersenne muchos siglos antes que este, y encontró una fuerte relación entre ellos y los números perfectos.  Concretamente,  el último resultado de la parte de teoría de números de sus *Elementos* establece que si $M$ es un  primo de Mersenne, entonces $M(M+1)/2$ es un número perfecto par. Comprueba esta afirmación para los diez primeros primos de Mersenne. 

*Observación previa:* por los apartados anteriores sé que $M_n$ es primo para 2, 3, 5, 7, 13, 17, 19, 31, 127 (conocido por Mersenne, apartado c)), y en el apartado d) lo hemos visto para 61, 89, 107, 521, 607, 1279. Es decir, los diez valores más pequeños de $n$ para los que sabemos que $M_n$ es primo son 2, 3, 5, 7, 13, 17, 19, 31, 61, 89. Realmente no sé seguro si estos son los diez primeros primos de Mersenne: voy a comprobarlo:



In [6]:
# Definimos los primeros 10 primos de Mersenne.
lista_mersene = []
for n in range(1, 100): # Con un bucle hasta el 100 conseguimos los 10 primeros.
    valor = (2**n) - 1
    if valor == 1:
        continue
    else:
        primo = is_prime(valor)
        if primo == True:
            lista_mersene.append(valor)

show("Estos son los primeros 10 números de Mersene:")
show(lista_mersene)

# Comprobamos si M(M + 1)/2 es un número perfecto par para estos números.
for i in lista_mersene:
    nuevo_valor = i*(i+1)/2
    resultado = perfecto(nuevo_valor)
    if resultado == True:
        show(f"Número perfecto: {nuevo_valor}. Corresponde al número de Mersene: {i}")


'Estos son los primeros 10 números de Mersene:'

[3,
 7,
 31,
 127,
 8191,
 131071,
 524287,
 2147483647,
 2305843009213693951,
 618970019642690137449562111]

'Número perfecto: 6. Corresponde al número de Mersene: 3'

'Número perfecto: 28. Corresponde al número de Mersene: 7'

'Número perfecto: 496. Corresponde al número de Mersene: 31'

'Número perfecto: 8128. Corresponde al número de Mersene: 127'

'Número perfecto: 33550336. Corresponde al número de Mersene: 8191'

'Número perfecto: 8589869056. Corresponde al número de Mersene: 131071'

'Número perfecto: 137438691328. Corresponde al número de Mersene: 524287'

'Número perfecto: 2305843008139952128. Corresponde al número de Mersene: 2147483647'

'Número perfecto: 2658455991569831744654692615953842176. Corresponde al número de Mersene: 2305843009213693951'

'Número perfecto: 191561942608236107294793378084303638130997321548169216. Corresponde al número de Mersene: 618970019642690137449562111'

__________
**f)** Muchos siglos después, Euler demostró el recíproco: si un número $n$ es perfecto y par, entonces es de la forma $M(M+1)/2$ para algún primo de Mersenne. Obtén la lista de todos los números perfectos pares menores o iguales que $M_{13}(M_{13}+1)/2$ y comprueba que todos ellos son de la forma $M(M+1)/2$ para algún primo de Mersenne $M$.

In [39]:
#lista de todos los perfectos pares menores que M13*...: (cuidado, a sage le lleva un tiempo)
mtrece = (2^13-1)*2^12
lista_perfectos_pares = []
for m in range(2,mtrece+1,2):
    if perfecto(m):
        lista_perfectos_pares.append(m)
lista_perfectos_pares

#lista de los M(M+1)/2 donde M es un primo de Mersenne menor que M13
lista_mersenne = []
for n in range(1,14):
    if 2^n-1 in Primes():
        lista_mersenne.append((2^n-1)* 2^(n-1))
lista_mersenne

KeyboardInterrupt: 

____________
**g)** A día de hoy no se sabe si hay algún número perfecto impar. Comprueba que no hay ninguno menor que un millón.

In [2]:
lista_impares = []
for i in range(1, 1000000):
    if i%2 == 0:
        continue
    else:
        lista_impares.append(i)

for i in lista_impares:
    resultado = perfecto(i)
    if resultado == False:
        continue
    else:
        print(f"El número impar {i} es perfecto.")

# No se imprime nada por pantalla así que podemos decir que no hay ningún número impar perfecto
# menor a un millón.
    